# Generated by Django 6.0.6 on 2026-06-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commandstat',
            unique_together={('bot_name', 'command')},
        ),
    ]
